In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
customers = pd.read_csv('/content/customers.csv')

In [ ]:
sales = pd.read_csv('/content/sales.csv')

In [ ]:
products = pd.read_csv('/content/products.csv')

In [ ]:
stores = pd.read_csv('/content/stores.csv')

In [ ]:
customers.head()

  customer_id  age  gender  loyalty_member   join_date
0     C000001   40    Male               1  2025-05-21
1     C000002   47    Male               0  2021-12-26
2     C000003   58  Female               1  2022-09-13
3     C000004   25  Female               0  2025-02-27
4     C000005   43    Male               0  2023-08-31

In [ ]:
customers.shape

(50000, 5)

In [ ]:
products.shape

(200, 6)

In [ ]:
customers.columns
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     50000 non-null  object
 1   age             50000 non-null  int64
 2   gender          50000 non-null  object
 3   loyalty_member  50000 non-null  int64
 4   join_date       50000 non-null  object
dtypes: int64(2), object(3)
memory usage: 1.9+ MB

In [ ]:
sales.head()

,order_id,order_date,product_id,store_id,customer_id,quantity,unit_price,discount,revenue,cost,profit
0,0RD00000001,2023-01-07,P0080,S093,C040749,5,14.43,0.15,61.33,42.77,18.56
1,0RD00000002,2023-10-22,P0173,S065,C020161,3,12.01,0.00,36.03,19.06,16.97
2,0RD00000003,2023-05-07,P0115,S078,C048069,2,10.02,0.00,20.04,10.29,9.75
3,0RD00000004,2024-06-23,P0186,S088,C047901,2,14.66,0.10,26.39,16.35,10.04
4,0RD00000005,2024-09-24,P0197,S054,C033950,1,12.34,0.00,12.34,7.94,4.40

In [ ]:
sales.shape

(1000000, 11)

In [ ]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 11 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   order_id     1000000 non-null  object
 1   order_date   1000000 non-null  object
 2   product_id   1000000 non-null  object
 3   store_id     1000000 non-null  object
 4   customer_id  1000000 non-null  object
 5   quantity     1000000 non-null  int64
 6   unit_price   1000000 non-null  float64
 7   discount     1000000 non-null  float64
 8   revenue      1000000 non-null  float64
 9   cost         1000000 non-null  float64
 10  profit       1000000 non-null  float64
dtypes: float64(5), int64(1), object(5)
memory usage: 83.9+ MB

In [ ]:
products.head()

  product_id           product_name    brand category  cocoa_percent  weight_g
0      P0001    White Chocolate 80%     Mars  Truffle             80       120
1      P0002     Dark Chocolate 70%  Cadbury  Praline             70       100
2      P0003  Truffle Chocolate 70%  Hershey  Praline             70       120
3      P0004     Milk Chocolate 50%     Mars  Praline             50        80
4      P0005    White Chocolate 70%  Ferrero    White             70        50

In [ ]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     200 non-null    object
 1   product_name   200 non-null    object
 2   brand          200 non-null    object
 3   category       200 non-null    object
 4   cocoa_percent  200 non-null    int64
 5   weight_g       200 non-null    int64
dtypes: int64(2), object(4)
memory usage: 9.5+ KB

In [ ]:
stores.head()

  store_id         store_name       city country store_type
0     S001  Chocolate Store 1   New York  Canada     Retail
1     S002  Chocolate Store 2  Melbourne  Canada       Mall
2     S003  Chocolate Store 3     Berlin  France       Mall
3     S004  Chocolate Store 4      Paris      UK    Airport
4     S005  Chocolate Store 5     Sydney     USA     Online

In [ ]:
stores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   store_id    100 non-null    object
 1   store_name  100 non-null    object
 2   city        100 non-null    object
 3   country     100 non-null    object
 4   store_type  100 non-null    object
dtypes: object(5)
memory usage: 4.0+ KB

In [ ]:
#data type conversion

In [ ]:
customers['join_date'] = pd.to_datetime(customers['join_date'])

In [ ]:
sales['order_date'] = pd.to_datetime(sales['order_date'])

In [ ]:
#data cleaning

In [ ]:
customers.isnull().sum().sum()

np.int64(0)

In [ ]:
sales.isnull().sum()

order_id       0
order_date     0
product_id     0
store_id       0
customer_id    0
quantity       0
unit_price     0
discount       0
revenue        0
cost           0
profit         0
dtype: int64

In [ ]:
products.isnull().sum().sum()

np.int64(0)

In [ ]:
stores.isnull().sum().sum()

np.int64(0)

In [ ]:
customers.duplicated().sum()

np.int64(0)

In [ ]:
sales.duplicated().sum()

np.int64(0)

In [ ]:
products.duplicated().sum()

np.int64(0)

In [ ]:
stores.duplicated().sum()

np.int64(0)

In [ ]:
sales = sales.dropna()

In [ ]:
sales.isnull().sum().sum()

np.int64(0)

In [ ]:
sales.shape

(1000000, 11)

In [ ]:
products.shape

(200, 6)

In [ ]:
stores.shape

(100, 5)

In [ ]:
customers['customer_id'].nunique(), len(customers)

(50000, 50000)

In [ ]:
products['product_id'].nunique(), len(products)

(200, 200)

In [ ]:
stores['store_id'].nunique(), len(stores)

(100, 100)

In [ ]:
sales['order_id'].nunique(), len(sales)

(1000000, 1000000)

In [ ]:
#feature engineering

In [ ]:
sales['order_year'] = sales['order_date'].dt.year

In [ ]:
sales['order_year'].head()

0    2023
1    2023
2    2023
3    2024
4    2024
Name: order_year, dtype: int32

In [ ]:
sales['order_month'] = sales['order_date'].dt.month

In [ ]:
sales['order_month'].head()

0     1
1    10
2     5
3     6
4     9
Name: order_month, dtype: int32

In [ ]:
sales['order_monthname'] = sales['order_date'].dt.month_name()

In [ ]:
sales['order_monthname'].head()

0      January
1      October
2          May
3         June
4    September
Name: order_monthname, dtype: object

In [ ]:
sales['order_qtr'] = sales['order_date'].dt.quarter

In [ ]:
sales['order_qtr'].head()

0    1
1    4
2    2
3    2
4    3
Name: order_qtr, dtype: int32

In [ ]:
sales['day_of_week'] = sales['order_date'].dt.day_name()

In [ ]:
sales['profit_margin'] = round((sales['profit'] / sales['revenue']) * 100, 2)

In [ ]:
sales['profit_margin'].head()

0    30.26
1    47.10
2    48.65
3    38.04
4    35.66
Name: profit_margin, dtype: float64

In [ ]:
customers.to_csv('customers_upd.csv', index = False)
sales.to_csv('sales_upd.csv', index = False)
products.to_csv('products_upd.csv', index = False)
stores.to_csv('stores_upd.csv', index = False)

In [ ]:
from google.colab import files

files.download('customers_upd.csv')
files.download('sales_upd.csv')
files.download('products_upd.csv')
files.download('stores_upd.csv')

In [ ]:
stores.nunique()

store_id      100
store_name    100
city            7
country         6
store_type      4
dtype: int64